name: Add PR to Project Board

on:
  pull_request:
    types: [opened, reopened]

jobs:
  automate-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Add Pull Request to Project Board
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "DEMO Project"
          github-token: ${{ secrets.MY_TOKEN }}
          column: "To triage"
